#' Plot Step Results from brms Model Fits
#'
#' @param step_df A data frame generated by the \code{get_step()} function. 
#'  
#' @param compare_step_df Optional. A second data frame generated by \code{get_step()} 
#'   to be overlaid or compared against the primary \code{step_df}. Defaults to NULL.
#'
#' @return A \code{ggplot} object visualising the impact of each explanatory variable on CPUE standardisation.
#' @import ggplot2
#' @import dplyr
#' @importFrom cowplot theme_cowplot 
#' @export

plot_step <- function(step_df, compare_step_df = NULL, custom_theme = theme_cowplot(), custom_palette = default_palette){
  
  model_names <- levels(step_df$Model)
  # Generate the background data for every facet
  # For each step, we take all data from that step and all previous steps
  df_all_steps <- lapply(seq_along(model_names), function(i) {
    step_df %>%
      filter(as.numeric(Model) <= i) %>%
      mutate(
        FacetTarget = factor(model_names[i]),
        LineType = case_when(
          as.numeric(Model) == i     ~ 'Current',
          as.numeric(Model) == i - 1 ~ 'Previous',
          TRUE                       ~ 'Reduced'
        )
      )
  })%>%bind_rows()

  legend_labels <- c(
    'Reduced' = 'Reduced models',
    'Previous'   = 'Before adding current predictor',
    'Current'    = 'Current'
  )
  # ---Comparison logic---
  col1 <- custom_palette[['main']]
  if(!is.null(compare_step_df)){
    
    # transform comparison df and merge it with  all steps df
    df_all_steps<- df_all_steps %>%
      bind_rows(compare_step_df %>%
                  mutate(FacetTarget = Model,
                         LineType = 'Compare')) 
    
    legend_labels <- c(legend_labels, 'Compare'    = paste('Previous update to', max(as.numeric(as.character(compare_step_df$level)))))
    col1 <- custom_palette[['current']] 
  }
  # ---End of comparison logic---
  
  
  df_all_steps$LineType <- factor(df_all_steps$LineType, levels = c('Reduced', 'Previous', 'Compare', 'Current')) 
  
  # ---Arrange plot styling elements---
  # Create dataframe that governs divider lines between facets
  all_levels <- levels(df_all_steps$FacetTarget)
  divider_data <- data.frame(
                            FacetTarget = factor(all_levels[-length(all_levels)], levels = all_levels), 
                            y_line = -Inf                                     
                            )
  
  if (missing(custom_theme)) {
    # Settings for the default theme_cowplot()
    border_setting <- element_rect(colour = custom_palette['helper'], fill = NA, linewidth = 0.5)
    spacing_setting <- unit(0, 'lines')
  } else {
    # Settings for when a user passes their own theme
    border_setting <- element_blank()
    spacing_setting <- unit(1, 'lines')
  } 
  
  # ---Plot code---
  p <- ggplot(df_all_steps %>% arrange(LineType), aes(x = level, y = median, group = interaction(Model, LineType))) +
    geom_line(aes(color = LineType, linetype = LineType)) +
    scale_color_manual(values = c('Current' = col1, 'Compare' = custom_palette[['previous']], 'Reduced' = custom_palette[['reduced']], 'Previous' = col1 ),
                       labels = legend_labels) +
    scale_linetype_manual(values = c('Current' = 1, 
                                     'Compare' = 1, 
                                     'Reduced' = 1, 
                                     'Previous' = 2),
                          labels = legend_labels) +
    geom_point(data = filter(df_all_steps, LineType == 'Current'), 
               color = col1) +
    
    geom_label(data = df_all_steps %>%
                 group_by(FacetTarget) %>%
                 summarize(Model = last(Model),
                           
                           # Following mutate logic is all about location of facet labels
                           is_upward = last(median) > first(median),
                           # Proximity Check: Is the start of the series closer to bottom or top of y-range?
                           is_starting_low = mean(head(median)) < max(median) - mean(head(median)),
                           # If it starts low and goes up -> Place at TOP (y = Inf), otherwise place at BOTTOM (y = -Inf)
                           y_pos = if_else(is_starting_low & is_upward, Inf, -Inf),
                           v_just = if_else(y_pos == Inf, 1.1, -0.1),
                 ),
               aes(label = FacetTarget, x = -Inf, y = y_pos, vjust = v_just),
               inherit.aes = FALSE,
               # Fixed alignment settings:
               hjust = 0,
               # label.padding = unit(1, 'lines'),
               linewidth = NA,
               fill = NA,
               size = 9 / .pt) +
    geom_hline(
  data = divider_data, 
  aes(yintercept = y_line), 
  color = custom_palette['helper'], 
  linewidth = 0.5
) +
    labs(x = 'Fishing year', y = 'Index') +
    scale_y_continuous(limits = c(0, NA), 
                       expand = expansion(mult = c(0.1, 0.1)), 
                       guide = guide_axis(check.overlap = TRUE),
                       breaks = function(x) unique(pretty(x)[pretty(x) != min(x)]) )+
    facet_wrap(~FacetTarget, ncol = 1) +
    custom_theme +
    theme(
      legend.key.width = unit(2.5, 'lines'),
      legend.position = ifelse(is.null(compare_step_df), 'none', 'top'),
      legend.justification = 'right',
      legend.title = element_blank(),
      strip.background = element_blank(),
      strip.text = element_blank(),       
      panel.border = border_setting,     
      panel.spacing = spacing_setting,
      axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1),
      axis.title.x = element_text(margin = margin(t = 15)),
      plot.background = element_rect(fill = 'white', color = NA),
    )
  
  return(p)
}
